//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBiEmbeddedScratchpad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBiEmbeddedScratchpad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///  margin: 0;
        ///  padding: 0;
        ///  background-color: #EEE;
        ///}
        ///
        ///#toolbar {
        ///  padding: 8px;
        ///  background-color: black;
        ///  color: white;
        ///}
        ///
        ///  #toolbar button {
        ///    font-size: 10px;
        ///    width: 132px;
        ///    border-radius: 8px;
        ///    padding: 3px;
        ///  }
        ///
        ///  #toolbar .radio-group {
        ///    color: black;
        ///    background-color: #EDBE11;
        ///    padding: 4px;
        ///    padding-right: 12px;
        ///    margin-right: 12px;
        ///    ;
        ///    display: inline-block;
        ///  }
        ///
        ///  #toolbar .radio-group-label {
        ///    color: black;
        ///    font-weight: bold;
        ///    margin-left:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app_css {
            get {
                return ResourceManager.GetString("app_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppIcon_png {
            get {
                object obj = ResourceManager.GetObject("AppIcon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] background_jpg {
            get {
                object obj = ResourceManager.GetObject("background_jpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedDashboardId = &quot;@EmbedDashboardId&quot;;
        ///    var embedUrl = &quot;@Emb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedDashboard_html {
            get {
                return ResourceManager.GetString("EmbedDashboard_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedDashboardId = &quot;@EmbedDashboardId&quot;;
        ///    var embedTileId = &quot;@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedDashboardTile_html {
            get {
                return ResourceManager.GetString("EmbedDashboardTile_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // Get data required for embedding
        ///    var embedWorkspaceId= &quot;@EmbedW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedNewReport_html {
            get {
                return ResourceManager.GetString("EmbedNewReport_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.min.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi-report-authoring.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///    &lt;button  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedNewReportCreateVisuals_html {
            get {
                return ResourceManager.GetString("EmbedNewReportCreateVisuals_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot; style=&quot;display:none;&quot;&gt;
        ///    &lt;button type=&quot;button&quot; id=&quot;toggleEdit&quot; style=&quot;font-size:14px&quot;&gt;Toggle E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedNewReportWithSaveAsRedirect_html {
            get {
                return ResourceManager.GetString("EmbedNewReportWithSaveAsRedirect_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // Get data required for embedding
        ///    var datasetId = &quot;@DatasetId&quot;;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedQna_html {
            get {
                return ResourceManager.GetString("EmbedQna_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@Embed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReport_html {
            get {
                return ResourceManager.GetString("EmbedReport_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/bootstrap.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/bootstrap.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportConfiguration_html {
            get {
                return ResourceManager.GetString("EmbedReportConfiguration_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportEditMode_html {
            get {
                return ResourceManager.GetString("EmbedReportEditMode_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportVisual_html {
            get {
                return ResourceManager.GetString("EmbedReportVisual_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot; style=&quot;font-size: 24pt;text-align:center;&quot; &gt;
        ///    &amp;nbsp;
        ///  &lt;/div&gt;
        ///
        ///  &lt;div id=&quot;reportContainer&quot; /&gt;
        ///  
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithBookmarkCarousel_html {
            get {
                return ResourceManager.GetString("EmbedReportWithBookmarkCarousel_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;leftnav&quot; style=&quot;float:left; width:240px;&quot;&gt;
        ///    &lt;h3&gt;Bookmarks&lt;/h3&gt;
        ///    &lt;div id=&quot;loading&quot;&gt;
        ///      &lt;img title=&quot;L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithBookmarks_html {
            get {
                return ResourceManager.GetString("EmbedReportWithBookmarks_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot;;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithBookmarksPlayMode_html {
            get {
                return ResourceManager.GetString("EmbedReportWithBookmarksPlayMode_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    var reportContainer = document.getElementById(&apos;embedContainer&apos;);
        ///
        ///    var configBootstrap = {
        ///      type: &apos;report&apos;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithBootstrap_html {
            get {
                return ResourceManager.GetString("EmbedReportWithBootstrap_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///
        ///    &lt;div class=&quot;radio-group&quot;&gt;
        ///      &lt;span class=&quot;radio-group-label&quot;&gt;Language:&lt;/span&gt;
        ///      &lt;input type=&quot;radio&quot; name=&quot;language&quot; value=&quot;en&quot; id=&quot;en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithConfigurationOptions_html {
            get {
                return ResourceManager.GetString("EmbedReportWithConfigurationOptions_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;reportContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithContextMenus_html {
            get {
                return ResourceManager.GetString("EmbedReportWithContextMenus_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///
        ///    &lt;div class=&quot;radio-group&quot;&gt;
        ///      &lt;span class=&quot;radio-group-label&quot;&gt;Contrast Mode:&lt;/span&gt;
        ///      &lt;input type=&quot;radio&quot; name=&quot;contrast&quot; value=&quot;none [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithContrastMode_html {
            get {
                return ResourceManager.GetString("EmbedReportWithContrastMode_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;reportContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot;;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithCorrelationId_html {
            get {
                return ResourceManager.GetString("EmbedReportWithCorrelationId_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;reportContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithCustomExportCommand_html {
            get {
                return ResourceManager.GetString("EmbedReportWithCustomExportCommand_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;leftnav&quot; style=&quot;float:left;&quot; &gt;
        ///
        ///    &lt;h3&gt;Custom Filtering &lt;/h3&gt;
        ///
        ///    &lt;div id=&quot;loading&quot; hidden &gt;
        ///      &lt;img [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithCustomFiltering_html {
            get {
                return ResourceManager.GetString("EmbedReportWithCustomFiltering)html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///    &lt;div class=&quot;radio-group&quot;&gt;
        ///      &lt;span class=&quot;radio-group-label&quot;&gt;Select Layout:&lt;/span&gt;
        ///      &lt;input type=&quot;radio&quot; name=&quot;layout&quot; value=&quot;default&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithCustomLayout_html {
            get {
                return ResourceManager.GetString("EmbedReportWithCustomLayout_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;reportContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedRepo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithDynamicBinding_html {
            get {
                return ResourceManager.GetString("EmbedReportWithDynamicBinding_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@Embed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithEventLogging_html {
            get {
                return ResourceManager.GetString("EmbedReportWithEventLogging_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/bootstrap.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/bootstrap.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithFirstPartyToken_html {
            get {
                return ResourceManager.GetString("EmbedReportWithFirstPartyToken_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithHyperlinkNavigation_html {
            get {
                return ResourceManager.GetString("EmbedReportWithHyperlinkNavigation_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///
        ///    &lt;div class=&quot;radio-group&quot;&gt;
        ///      &lt;span class=&quot;radio-group-label&quot;&gt;Language:&lt;/span&gt;
        ///      &lt;input type=&quot;radio&quot; name=&quot;language&quot; value=&quot;en-US&quot; i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithLocalizedLanguage_html {
            get {
                return ResourceManager.GetString("EmbedReportWithLocalizedLanguage_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///  &lt;div id=&quot;leftnav&quot; style=&quot;float:left; width:240px;&quot;&gt;
        ///    &lt;h3&gt;Page Navigation&lt;/h3&gt;
        ///    &lt;div id=&quot;loading&quot;&gt;
        ///      &lt;img tit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithPageNavigation_html {
            get {
                return ResourceManager.GetString("EmbedReportWithPageNavigation_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;embedContainer&quot; /&gt;
        ///
        ///  &lt;script&gt;
        ///
        ///    // data required for embedding Power BI report
        ///    var embedReportId = &quot;@EmbedReportId&quot;;
        ///    var embedUrl = &quot;@EmbedUrl&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithPhasedLoading_html {
            get {
                return ResourceManager.GetString("EmbedReportWithPhasedLoading_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot; style=&quot;text-align:center;&quot;&gt;
        ///    &lt;button type=&quot;button&quot; id=&quot;loadReportAllData&quot; style=&quot;font-size:14px&quot;&gt;All Regions&lt;/button&gt;
        ///    &lt;button type=&quot;button&quot; id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithRLS_html {
            get {
                return ResourceManager.GetString("EmbedReportWithRLS_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///
        ///    &lt;div class=&quot;radio-group&quot;&gt;
        ///      &lt;span class=&quot;radio-group-label&quot;&gt;Select Theme:&lt;/span&gt;
        ///      &lt;input type=&quot;radio&quot; name=&quot;theme&quot; value=&quot;default&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithThemeLoading_html {
            get {
                return ResourceManager.GetString("EmbedReportWithThemeLoading_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0;padding:0;background-color:#EEE;&quot;&gt;
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///    &lt;button type=&quot;button&quot; id=&quot;filters&quot; &gt;Filters&lt;/button&gt;
        ///    &lt;button type=&quot;button&quot; id=&quot;book [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithToolbar_html {
            get {
                return ResourceManager.GetString("EmbedReportWithToolbar_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///
        ///  &lt;div id=&quot;toolbar&quot;&gt;
        ///
        ///
        ///    &lt;div class=&quot;radio-group&quot;&gt;
        ///      &lt;span class=&quot;radio-group-label&quot;&gt;Background:&lt;/span&gt;
        ///      &lt;input type=&quot;radio&quot; name=&quot;background&quot; value=&quot;sol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithTransparentBackground_html {
            get {
                return ResourceManager.GetString("EmbedReportWithTransparentBackground_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;@AppName&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;loading&quot; style=&quot;text-align:center;&quot;&gt;
        ///    &lt;div style=&quot;font-size:52px;margin:32px;&quot;&gt;Loading report...&lt;/div&gt;
        ///    &lt;div&gt;
        ///      &lt;img title=&quot;Loading...&quot; src=&quot;css/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbedReportWithWhiteLabelLoading_html {
            get {
                return ResourceManager.GetString("EmbedReportWithWhiteLabelLoading_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] favicon_ico {
            get {
                object obj = ResourceManager.GetObject("favicon_ico", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v3.7.0
        /// * https://jquery.com/
        /// *
        /// * Copyright OpenJS Foundation and other contributors
        /// * Released under the MIT license
        /// * https://jquery.org/license
        /// *
        /// * Date: 2023-05-11T18:29Z
        /// */
        ///(function (global, factory) {
        ///
        ///	&quot;use strict&quot;;
        ///
        ///	if (typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot;) {
        ///
        ///		// For CommonJS and CommonJS-like environments where a proper `window`
        ///		// is present, execute the factory and get jQuery.
        ///		// For environments that do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_js {
            get {
                return ResourceManager.GetString("jquery_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] loading_gif {
            get {
                object obj = ResourceManager.GetObject("loading_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] loading2_gif {
            get {
                object obj = ResourceManager.GetObject("loading2_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] loading3_gif {
            get {
                object obj = ResourceManager.GetObject("loading3_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] menuicon_png {
            get {
                object obj = ResourceManager.GetObject("menuicon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // powerbi-client v2.22.3
        ///// Copyright (c) Microsoft Corporation.
        ///// Licensed under the MIT License.
        ///(function webpackUniversalModuleDefinition(root, factory) {
        ///	if(typeof exports === &apos;object&apos; &amp;&amp; typeof module === &apos;object&apos;)
        ///		module.exports = factory();
        ///	else if(typeof define === &apos;function&apos; &amp;&amp; define.amd)
        ///		define([], factory);
        ///	else if(typeof exports === &apos;object&apos;)
        ///		exports[&quot;powerbi-client&quot;] = factory();
        ///	else
        ///		root[&quot;powerbi-client&quot;] = factory();
        ///})(this, () =&gt; {
        ///return /******/ (() =&gt; { // webpackBootstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string powerbi_js {
            get {
                return ResourceManager.GetString("powerbi_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;file&quot;:&quot;powerbi.js&quot;,&quot;mappings&quot;:&quot;;;;AAAA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA,CAAC;AACD;;;;;;;;;ACVA;AACA;AACA,IAAI,IAAyD;AAC7D;AACA,MAAM,EAKkC;AACxC,CAAC;AACD,qCAAqC;AACrC;AACA;AACA;AACA;AACA,mBAAmB,8BAAmB;AACtC;AACA;AACA;AACA;AACA;AACA;AACA;AACA,uBAAuB;AACvB;AACA;AACA;AACA;AACA;AACA,0EAA0E,8BAAmB;AAC7F;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA,UAAU,8BAAmB;AAC7B;AACA;AACA,UAAU,8BAAmB;AAC7B;AACA;AACA,UAAU,8BAAmB;AAC7B;AACA;AACA,iBAAiB,8BAAmB;AACpC,UAAU;AACV;AACA;AACA;AACA;;AAEA;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string powerbi_js_map {
            get {
                return ResourceManager.GetString("powerbi.js_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // powerbi-client v2.22.3
        ///// Copyright (c) Microsoft Corporation.
        ///// Licensed under the MIT License.
        ////*! For license information please see powerbi.js.LICENSE.txt */
        ///!function(t,e){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?module.exports=e():&quot;function&quot;==typeof define&amp;&amp;define.amd?define([],e):&quot;object&quot;==typeof exports?exports[&quot;powerbi-client&quot;]=e():t[&quot;powerbi-client&quot;]=e()}(this,(()=&gt;(()=&gt;{var t={615:function(t){var e;e=function(){return function(t){var e={};function r(i){if(e[i])return e[i].exports;var [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string powerbi_min_js {
            get {
                return ResourceManager.GetString("powerbi.min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! For license information please see powerbi-report-authoring.js.LICENSE.txt */
        ///!function(e,t){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?module.exports=t(require(&quot;powerbi-client&quot;)):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;powerbi-client&quot;],t):&quot;object&quot;==typeof exports?exports[&quot;powerbi-report-authoring&quot;]=t(require(&quot;powerbi-client&quot;)):e[&quot;powerbi-report-authoring&quot;]=t(e[&quot;powerbi-client&quot;])}(self,(e=&gt;(()=&gt;{var t={913:(e,t)=&gt;{Object.defineProperty(t,&quot;__esModule&quot;,{value:!0}),t.Config=void 0;var r=funct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string powerbi_report_authoring_js {
            get {
                return ResourceManager.GetString("powerbi-report-authoring_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;Report Inspector&lt;/title&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///  &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;script src=&quot;scripts/jquery.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;scripts/powerbi.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;output-display&quot; style=&quot;float:right; width:400px; overflow: auto;&quot;&gt;
        ///    &lt;h3&gt;Visuals in this report&lt;/h3&gt;
        ///    &lt;table id=&quot;visual-table&quot;&gt;&lt;/table&gt;
        ///    &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportInspector_html {
            get {
                return ResourceManager.GetString("ReportInspector_html", resourceCulture);
            }
        }
    }
}
